### PBS preamble

#!/bin/bash
#PBS -S /bin/bash
#PBS -A ACF-UTK0011

#PBS -N pimc
#PBS -q batch
#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00
#PBS -j oe
#PBS -o out_pimc
#PBS -t 0-499
#PBS -l qos=

# Do not send email
#PBS -M ecasiano@vols.utk.edu
#PBS -m n

cd $PBS_O_WORKDIR
module load gcc/10.1.0

./pimc.e -U 3.3 -D 1 -L 64 -N 64 -l 32 --beta 3.0 --bin-size 1000 --bins-wanted 1000 --mu 6 --subgeometry square --seed ${PBS_ARRAYID}


